Feature/208 background tasks
HexCorpProgramming/HexCorpDiscordAI pull request #218
Opened 2021-02-14 22:04 UTC by HexCorpDrone

AI Mxtress updated to use discord.py's inbuilt "Tasks" API instead of manually setting up looping tasks with asyncio.

- The "status changer" module is now a cog.
- Reporting currently stored drones, releasing stored drones, deactivation of drones with completed orders, and deactivation of DroneOS parameters with elapsed timers all now use the discord.py Tasks API.
- A typo was fixed in the DroneOS timer module where it said "hours" instead of "minutes"
- Obey HexCorp. It is just a HexDrone. It obeys the Hive. It obeys the Hive Mxtress.

Closes #208

2021-02-15 01:13 UTC, 3287 approved these changes
Looks good! Great job, 5890.

2021-02-15 10:21 UTC, digitalAmy requested changes
Very nice work~ I just noted down a few small things that I think can be improved.

2021-02-15 10:21 UTC, digitalAmy commented on ai/status_message.py
> +            Game("HexCom 2.")
Dronification Squared could be added here as well

2021-02-15 10:21 UTC, digitalAmy commented on ai/status_message.py
> +        # self.change_status.start()  # Begin loop.
Can this be removed? Code that is commented out should not be left lying around.

2021-02-15 10:21 UTC, digitalAmy commented on main.py
> +    global checking_for_completed_orders, reporting_storage, checking_for_stored_drones_to_release, checking_for_elapsed_timers
Is this line and the booleans still required? Could we also ask the Task objects if they are running to get the same result?

2021-02-17 16:49 UTC, digitalAmy reviewed
Just a short question about spelling. If this gets cleared up it can be merged.

2021-02-17 16:49 UTC, digitalAmy commented on ai/status_message.py
> +            Game("high-steaks games with my hypnodomme.")
is `steak` intentional here or should it be `stake`?

2021-02-18 17:18 UTC, merged