Feature/221 speech op enforcement split
HexCorpProgramming/HexCorpDiscordAI pull request #222
Opened 2021-02-15 21:24 UTC by HexCorpDrone

Speech optimization has been split into two modules.
- Speech optimization, the module that handles converting codes into messages.
- Speech optimization enforcement, a new module that handles the deletion of inappropriate messages by optimized drones.

This change allows speech code optimization to be used in previously blacklisted channels (moderation, orders reporting, etc) while still disabling enforced optimization.

Additional minor change: Fixed typo in the default mantra: "Hexcorp" > "HexCorp"

Closes #221 

Obey HexCorp. It is just a HexDrone. It obeys the Hive. It obeys the Hive Mxtress.

2021-02-17 17:06 UTC, digitalAmy requested changes
This was a good idea and also a clean implementation apart from some dead code. But very good work~

2021-02-17 17:06 UTC, digitalAmy commented on ai/speech_optimization.py
> -    drone_id = get_id(message.author.display_name)
This function is now empty apart from comments. It should be removed and the comments be moved or deleted.

(btw: interesting that this does not raise an error without a `pass` statement)

2021-02-17 18:57 UTC, 3287 requested changes
Other than what 9813 has already brought up, this is really clean work. Good job, 5890~

2021-02-18 17:12 UTC, digitalAmy approved these changes
Excellent work~

2021-02-18 17:13 UTC, merged