adding free storage configs
HexCorpProgramming/HexCorpDiscordAI pull request #407
Opened 2023-08-20 10:39 UTC by 3287

Adding a `is_free_storage` config to DroneOS, to allow each drone to specify whether they want to allow anyone to store it, or to restrict it to trusted users + Hive Mxtress.

closes #400.

2023-08-21 15:20 UTC, digitalAmy requested changes
Just a tiny thing with some unnecessary code.

2023-08-21 15:20 UTC, digitalAmy commented on src/ai/storage.py
> +            return False
This return is not necessary as the program flow will continue to another `return False`  in line 153 without it as well.

2023-08-21 15:20 UTC, digitalAmy commented on src/ai/storage.py
> +        return False
This return is not necessary as the program flow will continue to another return False in line 153 without it as well.

2023-08-23 02:51 UTC, 3287 commented
3287 :: Made changes, as requested!

2023-08-23 12:37 UTC, digitalAmy commented
Very nice.

2023-08-23 12:38 UTC, digitalAmy approved these changes
Very nice.

2023-08-23 12:39 UTC, merged